### ISSUE TITLE
Cannot restrict listen address for temboard-agent

### ISSUE THREAD

**Issue by Mika313** [dalibo/temboard-agent#515]
Hi all,

In configuration file, if i set `address` parameter in  `[temboard]` section i have the following error:
`Failed to start HTTPS server: [Errno 99] Cannot assign requested address.`
I set `address = 10.X.X.X` which is the Temboard UI IP in order to restrict the API exposure.

Thanks and Regards.

**Comment by pgiraud** [comment]
Hi,

The `address` parameter is not meant to be set to the IP of temBoard UI.

Since version 5.0 of the agent, the push mode (pushing data from the agent to the UI) has been dropped. Since then, the UI is pulling data. Thus, agents don't know anything about the UI. Before that, there was a dedicated `collector_url` parameter.

**Comment by Mika313** [comment]
Hi @pgiraud 
> The `address` parameter is not meant to be set to the IP of temBoard UI.

Then, what does
 _IP v4 address that the agent will listen on._ mean in the v7 documentaion?

**Comment by dlax** [comment]
> > The `address` parameter is not meant to be set to the IP of temBoard UI.
> 
> Then, what does
> _IP v4 address that the agent will listen on._ mean in the v7 documentation?

This should be an IP address of the agent host, not the UI one. So I think you cannot restrict connections to allow only the UI with this parameter but you can restrict the network associated with the IP address set there however. If you really need to restrict on the UI IP, using a firewall might be better suited.
